on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

name: check names

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Install convo R package
        run: |
          install.packages('remotes')
          remotes::install_github("emilyriederer/convo")
        shell: Rscript {0}

      - name: list files
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          $FILES > "check-file-names.csv"
          echo $FILES
      
      - name: Validate names
        run: |
          library(convo)
          convo <- read_convo("sql-config.yml")
          files <- readLines("check-file-names.csv")
          evaluate_convo(convo, files, sep = "-")
        shell: Rscript {0}
